name: krishiai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
    - fastapi>=0.68.0,<1.0.0
    - uvicorn>=0.15.0,<1.0.0
    - sqlalchemy>=1.4.23,<2.0.0
    - pydantic>=1.8.2,<2.0.0
    - bcrypt>=3.2.0,<4.0.0
    - requests>=2.26.0,<3.0.0
    - pandas>=1.3.3,<2.0.0
    - numpy>=1.21.2,<2.0.0
    - plotly>=5.3.1,<6.0.0
    - python-multipart>=0.0.5,<1.0.0
    - setuptools>=65.5.1
    - streamlit>=1.11.0
    - folium>=0.12.1
    - streamlit-folium>=0.10.0
    - geopy>=2.2.0
    - python-dotenv>=0.19.0
    - aiohttp>=3.8.1
    - python-jose>=3.3.0
    - passlib>=1.7.4
